In [1]:
import pandas as pd

In [19]:
b2017 = pd.read_csv("2017 bleaders.csv")
b2017.head()

,Name,Team,G,PA,HR,R,RBI,SB,BB%,K%,...,AVG,OBP,SLG,wOBA,wRC+,BsR,Off,Def,WAR,playerid
0,Aaron Judge,Yankees,155,678,52,128,114,9,18.7 %,30.7 %,...,0.284,0.422,0.627,0.430,173.0,0.0,60.8,-1.3,8.2,15640
1,Jose Altuve,Astros,153,662,24,112,81,32,8.8 %,12.7 %,...,0.346,0.410,0.547,0.405,160.0,4.0,52.6,-0.1,7.5,5417
2,Anthony Rendon,Nationals,147,605,25,81,100,7,13.9 %,13.6 %,...,0.301,0.403,0.533,0.394,142.0,1.5,34.3,15.8,6.9,12861
3,Giancarlo Stanton,Marlins,159,692,59,123,132,2,12.3 %,23.6 %,...,0.281,0.376,0.631,0.410,156.0,-2.4,47.8,-0.5,6.9,4949
4,Mike Trout,Angels,114,507,33,92,72,22,18.5 %,17.8 %,...,0.306,0.442,0.629,0.437,181.0,4.0,54.9,-3.5,6.9,10155

In [22]:
p2017 = pd.read_csv("2017 pleaders.csv")
p2017.head()

,Name,Team,W,L,SV,G,GS,IP,K/9,BB/9,HR/9,BABIP,LOB%,GB%,HR/FB,ERA,FIP,xFIP,WAR,playerid
0,Chris Sale,Red Sox,17,8,0,32,32,214.1,12.93,1.81,1.01,0.301,78.4 %,38.7 %,12.1 %,2.90,2.45,2.65,7.7,10603
1,Corey Kluber,Indians,18,4,0,29,29,203.2,11.71,1.59,0.93,0.267,82.6 %,44.5 %,13.5 %,2.25,2.50,2.52,7.3,2429
2,Max Scherzer,Nationals,16,6,0,31,31,200.2,12.02,2.47,0.99,0.245,80.7 %,36.5 %,10.8 %,2.51,2.90,3.28,6.0,3137
3,Luis Severino,Yankees,14,6,0,31,31,193.1,10.71,2.37,0.98,0.272,75.5 %,50.6 %,14.0 %,2.98,3.07,3.04,5.7,15890
4,Stephen Strasburg,Nationals,15,4,0,28,28,175.1,10.47,2.41,0.67,0.274,77.9 %,46.8 %,8.7 %,2.52,2.72,3.27,5.6,10131

In [21]:
f2016 = pd.read_csv("2016.csv")
f2016 = f2016[f2016["PLAYER"]!="PLAYER"]
f2016.head()

           PLAYER POS AGE  STATUS  2016 TEAM   NEW TEAM  YRS  RK   DOLLARS
0     A.J. Achter  RP  29  Signed     Angels     Tigers  NaN  NR  Minor Lg
1     Matt Albers  RP  35  Signed  White Sox  Nationals  NaN  NR  Minor Lg
2  Alexi Amarista  SS  28  Signed     Padres    Rockies    1  NR        --
3      Cody Asche  3B  27  Signed   Phillies  White Sox  NaN  NR  Minor Lg
4     Erick Aybar  SS  34  Signed     Tigers     Padres  NaN  NR  Minor Lg

In [34]:
ls = {}
tot2017 = 0
totIP = 0
totPA = 0
for index1, row1 in f2016.iterrows():
    fa = row1["PLAYER"]
#     ls[fa] = 0
    found = False
    search = b2017
#     n = findplayer(fa, f, s)
    if "P" in row1["POS"]:
        search = p2017
    else:
        search = b2017
    for index2, row2 in search.iterrows():
        if fa == row2["Name"]:
            war = row2["WAR"]
            if "P" in row1["POS"]:
                IP = row2["IP"]
                ls[fa] = {"WAR":war, "IP":IP}
                totIP += IP
            else:
                PA = row2["PA"]
                ls[fa] = {"WAR":war, "PA":PA}
                totPA += PA
            tot2017 += war
            found = True
        if found == True:
            break

In [26]:
# def findplayer(player, found, search):
#     for index2, row2 in search.iterrows():
#         if player == row2["Name"]:
#             war = row2["WAR"]
#             found = True
#     return {player:war, "found":found}

In [35]:
ls

{'Aaron Hill': {'PA': 80, 'WAR': -0.5},
 'Alejandro De Aza': {'PA': 70, 'WAR': -0.4},
 'Alexi Amarista': {'PA': 176, 'WAR': -1.2},
 'Austin Jackson': {'PA': 318, 'WAR': 1.8},
 'Blaine Boyer': {'IP': 41.1, 'WAR': 0.4},
 'Brandon Morrow': {'IP': 43.2, 'WAR': 1.7},
 'Bryan Holaday': {'PA': 29, 'WAR': -0.2},
 'Chris Coghlan': {'PA': 88, 'WAR': -0.5},
 'Christian Villanueva': {'PA': 32, 'WAR': 0.4},
 'Cody Asche': {'PA': 62, 'WAR': -0.9},
 'David Hernandez': {'IP': 55.0, 'WAR': 1.1},
 'Drew Stubbs': {'PA': 24, 'WAR': -0.3},
 'Emilio Bonifacio': {'PA': 44, 'WAR': -0.6},
 'Eric Fryer': {'PA': 83, 'WAR': -0.4},
 "Eric O'Flaherty": {'IP': 18.1, 'WAR': -0.2},
 'Erick Aybar': {'PA': 370, 'WAR': -0.2},
 'Geovany Soto': {'PA': 48, 'WAR': 0.0},
 'Gordon Beckham': {'PA': 18, 'WAR': -0.1},
 'Gregor Blanco': {'PA': 256, 'WAR': 0.5},
 'Hector Sanchez': {'PA': 143, 'WAR': -0.1},
 'Jaff Decker': {'PA': 62, 'WAR': -0.2},
 'Jared Hoying': {'PA': 77, 'WAR': -0.1},
 'Jarrod Saltalamacchia': {'PA': 26, 'WAR': -0.6},
 'Jose Pirela': {'PA': 344, 'WAR': 2.1},
 'Lucas Harrell': {'IP': 6.1, 'WAR': 0.0},
 'Mark Reynolds': {'PA': 593, 'WAR': 0.8},
 'Mat Latos': {'IP': 15.0, 'WAR': -0.3},
 'Matt Albers': {'IP': 61.0, 'WAR': 0.8},
 'Matt den Dekker': {'PA': 8, 'WAR': 0.0},
 'Peter Bourjos': {'PA': 203, 'WAR': 0.1},
 'Peter Moylan': {'IP': 59.1, 'WAR': 0.3},
 'Ryan Hanigan': {'PA': 112, 'WAR': -0.1},
 'Ryan Raburn': {'PA': 69, 'WAR': -0.1},
 'Seth Maness': {'IP': 9.2, 'WAR': -0.2},
 'Stephen Cardullo': {'PA': 32, 'WAR': -0.3},
 'Tommy Hunter': {'IP': 58.2, 'WAR': 1.2},
 'Vance Worley': {'IP': 71.2, 'WAR': 0.1},
 'Yusmeiro Petit': {'IP': 91.1, 'WAR': 2.2},
 'Zac Rosscup': {'IP': 7.2, 'WAR': 0.1}}

In [37]:
print(totIP, totPA, tot2017)

535.5 3367 6.100000000000001

In [36]:
print(len(ls), len(f2016))

39 73

In [39]:
t = 0
for e in ls:
    t += ls[e]["WAR"]
t

6.100000000000001